=== EPFL-ENAC/sxl-recrete-atlas/schema/parameters.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "definitions": {
        "SelectableGroupItem": {
            "properties": {
                "id": {
                    "type": "string"
                },
                "label": {
                    "type": "string"
                },
                "selected": {
                    "type": "boolean"
                },
                "children": {
                    "items": {
                        "$ref": "#/definitions/SelectableSingleItem"
                    },
                    "type": "array"
                },
                "tab": {
                    "type": "boolean"
                }
            },
            "type": "object"
        },
        "SelectableItem": {
            "anyOf": [
                {
                    "$ref": "#/definitions/SelectableSingleItem"
                },
                {
                    "$ref": "#/definitions/SelectableGroupItem"
                }
            ]
        },
        "ScaleEntry": {
            "properties": {
                "color": {
                    "type": "string"
                },
                "label": {
                    "type": "string"
                },
                "value": {
                    "type": "number"
                },
                "min": {
                    "type": "number"
                },
                "max": {
                    "type": "number"
                },
                "unit": {
                    "type": "string"
                },
                "range": {
                    "type": "array",
                    "maxItems": 2,
                    "items": {
                        "type": "number"
                    }
                }
            },
            "type": "object"
        },
        "LegendScale": {
            "properties": {
                "id": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "titleStart": {
                    "type": "string"
                },
                "titleEnd": {
                    "type": "string"
                },
                "unit": {
                    "type": "string"
                },
                "scale": {
                    "items": {
                        "$ref": "#/definitions/ScaleEntry"
                    },
                    "type": "array"
                }
            },
            "type": "object"
        },
        "SelectableSingleItem": {
            "properties": {
                "id": {
                    "type": "string"
                },
                "label": {
                    "type": "string"
                },
                "label_en": {
                    "type": "string"
                },
                "label_fr": {
                    "type": "string"
                },
                "selected": {
                    "type": "boolean"
                },
                "ids": {
                    "items": {
                        "type": "string"
                    },
                    "type": "array"
                },
                "measures": {
                    "items": {
                        "type": "string"
                    },
                    "type": "array"
                },
                "genre": {
                    "type": "string"
                },"legend": {
                    "type": "string"
                },
                "legendImage": {
                    "type": "string"
                },
                "legendScaleId": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "maplibregl.LngLat": {
            "properties": {
                "lat": {
                    "type": "number"
                },
                "lng": {
                    "type": "number"
                }
            },
            "type": "object"
        },
        "maplibregl.LngLatLike": {
            "anyOf": [
                {
                    "items": [
                        {
                            "type": "number"
                        },
                        {
                            "type": "number"
                        }
                    ],
                    "maxItems": 2,
                    "minItems": 2,
                    "type": "array"
                },
                {
                    "$ref": "#/definitions/maplibregl.LngLat"
                },
                {
                    "properties": {
                        "lat": {
                            "type": "number"
                        },
                        "lng": {
                            "type": "number"
                        }
                    },
                    "type": "object"
                },
                {
                    "properties": {
                        "lat": {
                            "type": "number"
                        },
                        "lon": {
                            "type": "number"
                        }
                    },
                    "type": "object"
                }
            ]
        }
    },
    "properties": {
        "center": {
            "$ref": "#/definitions/maplibregl.LngLatLike",
            "description": "Map default center coordinates"
        },
        "popupLayerIds": {
            "description": "Layers with popup",
            "items": {
                "type": "string"
            },
            "type": "array"
        },
        "selectableItems": {
            "description": "Selectable layers organization",
            "items": {
                "$ref": "#/definitions/SelectableItem"
            },
            "type": "array"
        },
        "subtitle": {
            "description": "Subtitle of the map",
            "type": "string"
        },
        "title": {
            "description": "Title of the map",
            "type": "string"
        },
        "zoom": {
            "description": "Map default zoom level",
            "type": "number"
        },
        "legendScales": {
            "items": {
                "$ref": "#/definitions/LegendScale"
            },
            "type": "array"
        }
    },
    "type": "object"
}

=== EPFL-ENAC/sxl-recrete-atlas/public/parameters.json
{
  "$schema": "https://raw.githubusercontent.com/EPFL-ENAC/alice-perl-eerl-urbtrees/main/schema/parameters.schema.json",
  "center": { "lat": 48.3246, "lng": 10 },
  "zoom": 4,
  "popupLayerIds": [],
  "selectableItems": [
    {
      "id": "theme",
      "label": "Theme",
      "children": [
        {
          "id": "classic",
          "label": "Classic",
          "selected": false
        },
        {
          "id": "arcgis",
          "label": "ArcGIS",
          "selected": true
        },
        {
          "id": "light",
          "label": "Light",
          "selected": false
        },
        {
          "id": "dark",
          "label": "Dark",
          "selected": false
        }
      ]
    },
    {
      "id": "projects",
      "label": "projects",
      "tab": true,
      "children": []
    }
  ],
  "title": "app_title",
  "subtitle": "app_subtitle"
}
